
version: 2.1

jobs:
  
  integration-dbt-utils-azuresql:
    docker:
      - image: dataders/pyodbc:1.2
    steps:
      # only needed until I add Git to the Docker container
      - run: &install-git
          name: "TEMP: install Git"
          command: |
            apt-get install -y git

      - checkout
      
      - run: &pull-submodules
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run: &setup-dbt
          name: "Setup dbt"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install git+https://github.com/dbt-msft/dbt-sqlserver.git@v0.19.0
            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml
      
      - run:
          name: "Run Tests - dbt-utils"
          # TODO re-implement dbt-utils's data tests
          command: |
            . venv/bin/activate
            cd integration_tests/dbt_utils
            dbt deps --target azuresql
            dbt seed --target azuresql --full-refresh
            dbt run --target azuresql --full-refresh
            dbt test --target azuresql --schema --exclude data_test_unique_where data_test_not_null_where data_test_mutually_exclusive_ranges_no_gaps data_test_mutually_exclusive_ranges_with_gaps data_test_relationships_where_table_2 test_urls test_url_host test_url_path data_test_at_least_one data_people data_test_expression_is_true data_test_not_constant
      
      - store_artifacts:
          path: ./logs
  integration-dbt-utils-synapse:
    docker:
      - image: dataders/pyodbc:1.2
    steps:
      # only needed until I add Git to the Docker container
      - run: *install-git

      - checkout
      
      - run: *pull-submodules

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install git+https://github.com/dbt-msft/dbt-synapse.git@v0.19.0-rc1
            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml
            pip list | grep "dbt"
      
      - run:
          name: "Run Tests - dbt-utils"
          command: |
            . venv/bin/activate
            cd integration_tests/dbt_utils
            dbt deps --target synapse
            dbt seed --target synapse --full-refresh
            dbt run --target synapse --full-refresh
            dbt test --target synapse --schema --exclude data_test_unique_where data_test_not_null_where data_test_mutually_exclusive_ranges_no_gaps data_test_mutually_exclusive_ranges_with_gaps data_test_relationships_where_table_2 test_urls test_url_host test_url_path data_test_at_least_one data_people data_test_expression_is_true data_test_not_constant
      
      - store_artifacts:
          path: ./logs


workflows:
  version: 2
  test-all:
    jobs:
      - integration-dbt-utils-azuresql: &dbt-context
          context: DBT_SYNAPSE_PROFILE
      - integration-dbt-utils-synapse: *dbt-context
